### ISSUE TITLE
如何在其他着色器里面添加这个？

### ISSUE THREAD

**Issue by mgdgfbhevdyeh** [bobcao3/Minecraft-GLSL-shaders-group#1]
RT

**Comment by bobcao3** [comment]
我会在之后添加它的wiki的，会讲每一个怎么用

对于第一个抗锯齿相对简单，直接丢进shaders文件夹然后把默认的compositex.fsh和vsh数字都加一，再把这个放进去

**Comment by mgdgfbhevdyeh** [comment]
还是关了吧，12月我就会了
